use std::collections::HashMap;
use macros::define_packet;
use crate::{
	define_enum,
	v1::{
		interaction::InteractionType,
		interface::{
			BlockChange,
			FluidChange,
		},
		ColorLight,
		ModelTransform,
		RangeF,
		RangeI,
		Rotation,
		Vector3f,
		Vector3i,
	},
};

define_enum! {
	pub enum Axis {
		X = 0,
		Y = 1,
		Z = 2
	}
}

define_enum! {
	pub enum BrushAxis {
		None = 0,
		Auto = 1,
		X = 2,
		Y = 3,
		Z = 4
	}
}

define_enum! {
	pub enum BrushOrigin {
		Center = 0,
		Bottom = 1,
		Top = 2
	}
}

define_enum! {
	pub enum BrushShape {
		Cube = 0,
		Sphere = 1,
		Cylinder = 2,
		Cone = 3,
		InvertedCone = 4,
		Pyramid = 5,
		InvertedPyramid = 6,
		Dome = 7,
		InvertedDome = 8,
		Diamond = 9,
		Torus = 10,
	}
}

define_enum! {
	pub enum BuilderToolAction {
		SelectionPosition1 = 0,
		SelectionPosition2 = 1,
		SelectionCopy = 2,
		HistoryUndo = 3,
		HistoryRedo = 4,
		ActivateToolMode = 5,
		DeactivateToolMode = 6,
	}
}

define_packet! {
	BuilderToolArg {
		fixed {
			required required: bool,
			required arg_type: BuilderToolArgType,
			opt(0, 1) bool_arg: BuilderToolBoolArg,
			opt(0, 2) float_arg: BuilderToolFloatArg,
			opt(0, 4) int_arg: BuilderToolIntArg,
			opt(0, 64) brush_shape_arg: BuilderToolBrushShapeArg,
			opt(0, 128) brush_origin_arg: BuilderToolBrushOriginArg,
			opt(1, 1) brush_axis_arg: BuilderToolBrushAxisArg,
			opt(1, 2) rotation_arg: BuilderToolRotationArg,
		}
		variable {
			opt(0, 8) string_arg: BuilderToolStringArg,
			opt(0, 16) block_arg: BuilderToolBlockArg,
			opt(0, 32) mask_arg: BuilderToolMaskArg,
			opt(1, 4) option_arg: BuilderToolOptionArg,
		}
	}
}

define_enum! {
	pub enum BuilderToolArgGroup {
		Tool = 0,
		Brush = 1
	}
}

define_enum! {
	pub enum BuilderToolArgType {
		Bool = 0,
		Float = 1,
		Int = 2,
		String = 3,
		Block = 4,
		Mask = 5,
		BrushShape = 6,
		BrushOrigin = 7,
		BrushAxis = 8,
		Rotation = 9,
		Option = 10,
	}
}

define_packet! {
	BuilderToolArgUpdate {
		fixed {
			required token: i32,
			required section: i32,
			required slot: i32,
			required group: BuilderToolArgGroup,
		}
		variable {
			opt(1) id: String,
			opt(2) value: String,
		}
	}
}

define_packet! {
	BuilderToolBlockArg {
		fixed {
			required allow_pattern: bool,
		}
		variable {
			opt(1) devault_value: String
		}
	}
}

define_packet! {
	BuilderToolBoolArg{
		default_value: bool
	}
}

define_packet! {
	BuilderToolBrushAxisArg {
		default_value: BrushAxis
	}
}

define_packet! {
	BuilderToolBrushData {
		fixed {
			opt(0, 1) width: BuilderToolIntArg,
			opt(0, 2) height: BuilderToolIntArg,
			opt(0, 4) thickness: BuilderToolIntArg,
			opt(0, 8) capped: BuilderToolBoolArg,
			opt(0, 16) shape: BuilderToolBrushShapeArg,
			opt(0, 32) origin: BuilderToolBrushOriginArg,
			opt(0, 64) origin_rotation: BuilderToolBoolArg,
			opt(0, 128) rotation_axis: BuilderToolBrushAxisArg,
			opt(1, 1) rotation_angle: BuilderToolRotationArg,
			opt(1, 2) mirror_axis: BuilderToolBrushAxisArg,
			opt(2, 8) use_mask_commands: BuilderToolBoolArg,
			opt(2, 16) invert_mask: BuilderToolBoolArg,
		}
		variable {
			opt(1, 4) material: BuilderToolBlockArg,
			opt(1, 8) favorite_materials: Vec<BuilderToolBlockArg>,
			opt(1, 16) mask_arg: BuilderToolMaskArg, // Funny enough, making this "mask" causes a name conflict with the generated byte mask
			opt(1, 32) mask_above: BuilderToolMaskArg,
			opt(1, 64) mask_not: BuilderToolMaskArg,
			opt(1, 128) mask_below: BuilderToolMaskArg,
			opt(2, 1) mask_adjacent: BuilderToolMaskArg,
			opt(2, 2) mask_neighbor: BuilderToolMaskArg,
			opt(2, 4) mask_commands: Vec<BuilderToolStringArg>,
		}
	}
}

define_packet! {
	BuilderToolBrushOriginArg {
		default_value: BrushOrigin
	}
}

define_packet! {
	BuilderToolBrushShapeArg {
		default_value: BrushShape
	}
}

define_packet! {
	BuilderToolEntityAction {
		action: EntityToolAction
	}
}

define_packet! {
	BuilderToolExtrudeAction {
		pos: Vector3i,
		normal: Vector3i
	}
}

define_packet! {
	BuilderToolFloatArg {
		default_value: f32,
		range: RangeF
	}
}

define_packet! {
	BuilderToolGeneralAction {
		action: BuilderToolAction
	}
}

define_packet! { BuilderToolHideAnchors {} }

define_packet! {
	BuilderToolIntArg {
		default_value: i32,
		range: RangeI
	}
}

define_packet! {
	BuilderToolLaserPointer {
		player_network_id: i32,
		start: Vector3i,
		end: Vector3i,
		color: i32,
		duration_ms: i32
	}
}

define_packet! {
	BuilderToolLineAction {
		start: Vector3i,
		end: Vector3i
	}
}

define_packet! {
	BuilderToolMaskArg {
		variable {
			opt(1) default_value: String
		}
	}
}

define_packet! {
	BuilderToolOnUseInteraction {
		interaction_type: InteractionType,
		pos: Vector3i,
		offset_for_pain_mode: Vector3i,
		is_alt_play_sculpt_brush_mod_down: bool,
		is_hold_down_interaction: bool,
		is_do_server_raytrace_for_position: bool,
		is_show_edit_notifications: bool,
		max_length_tool_ignore_history: i32,
		raycast_origin: Vector3f,
		raycast_direction: Vector3f
	}
}

define_packet! {
	BuilderToolOptionArg {
		variable {
			opt(1) default_value: String,
			opt(2) options: Vec<String>
		}
	}
}

define_packet! {
	BuilderToolPasteClipboard {
		pos: Vector3i
	}
}

define_packet! {
	BuilderToolRotateClipboard {
		angle: i32,
		axis: Axis
	}
}

define_packet! {
	BuilderToolRotationArg {
		default_value: Rotation
	}
}

define_packet! { BuilderToolSelectionToolAskForClipboard {} }

define_packet! {
	BuilderToolSelectionToolReplyWithClipboard {
		variable {
			opt(1) blocks_change: Vec<BlockChange>,
			opt(2) fluids_change: Vec<FluidChange>
		}
	}
}

define_packet! {
	BuilderToolSelectionTransform {
		fixed {
			opt(2) initial_selection_min: Vector3i,
			opt(4) initial_selection_max: Vector3i,
			opt(8) initial_rotation_origin: Vector3f,
			required cut_original: bool,
			required apply_transformation_to_selection_min_max: bool,
			required is_exiting_transform_mode: bool,
			opt(16) initial_paste_point_for_clipboard_paste: Vector3i,
		}
		variable {
			opt(1) transformation_matrix: Vec<f32>
		}
	}
}

define_packet! {
	BuilderToolSelectionUpdate {
		min: Vector3i,
		max: Vector3i
	}
}

define_packet! {
	BuilderToolSetEntityLight {
		fixed {
			required entity_id: i32,
			opt(1) light: ColorLight
		}
	}
}

define_packet! {
	BuilderToolSetEntityPickupEnabled {
		entity_id: i32,
		enabled: bool
	}
}

define_packet! {
	BuilderToolSetEntityScale {
		entity_id: i32,
		scale: f32
	}
}

define_packet! {
	BuilderToolSetEntityTransform {
		fixed {
			required entity_id: i32,
			opt(1) model_transform: ModelTransform
		}
	}
}

define_packet! {
	BuilderToolSetNPCDebug {
		entity_id: i32,
		enabled: bool
	}
}

define_packet! {
	BuilderToolSetTransformationModeState {
		enabled: bool
	}
}

define_packet! {
	BuilderToolShowAnchor {
		pos: Vector3i,
	}
}

define_packet! {
	BuilderToolsSetSoundSet {
		sound_set_index: i32
	}
}

define_packet! {
	BuilderToolStackArea {
		fixed {
			opt(1) selection_min: Vector3i,
			opt(2) selection_max: Vector3i,
			required normal: Vector3i,
			required num_stacks: i32,
		}
	}
}

define_packet! {
	BuilderToolState {
		fixed {
			required is_brush: bool
		}
		variable {
			opt(1) id: String,
			opt(2) brush_data: BuilderToolBrushData,
			opt(4) args: HashMap<String, BuilderToolArg>
		}
	}
}

define_packet! {
	BuilderToolStringArg {
		variable {
			opt(1) default_value: String
		}
	}
}

define_enum! {
	pub enum EntityToolAction {
		Remove = 0,
		Clone = 1,
		Freeze = 2
	}
}

define_packet! { PrefabUnselectPrefab { } }
